// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	Category string
}

type Expense struct {
	ID          int64
	User        sql.NullString
	Description string
	Category    sql.NullString
	Amount      float64
	CreatedDate time.Time
}

type User struct {
	Name         string
	Salt         []byte
	Hashpassword []byte
}
