// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"
)

const insertUser = `-- name: InsertUser :one
insert into users (name)
values (?)
returning id
`

func (q *Queries) InsertUser(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertUser, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
